version: "3.8"
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - 8000:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_laravel
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
  vendor:
